<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Account\Entities\ChartOfAccount;

class ChartOfAccountSeeder extends Seeder
{
    private $chart_of_accounts = [];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->chart_of_accounts = [
            [
                'code'              => 1,
                'name'              => 'Assets',
                'parent_name'       => 'COA',
                'level'             => 0,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 2,
                'name'              => 'Equity',
                'parent_name'       => 'COA',
                'level'             => 0,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 3,
                'name'              => 'Income',
                'parent_name'       => 'COA',
                'level'             => 0,
                'type'              => 'I',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 4,
                'name'              => 'Expense',
                'parent_name'       => 'COA',
                'level'             => 0,
                'type'              => 'E',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 5,
                'name'              => 'Liabilities',
                'parent_name'       => 'COA',
                'level'             => 0,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 101,
                'name'              => 'Non Current Asset',
                'parent_name'       => 'Assets',
                'level'             => 1,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 102,
                'name'              => 'Current Asset',
                'parent_name'       => 'Assets',
                'level'             => 1,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 301,
                'name'              => 'Product Sale',
                'parent_name'       => 'Income',
                'level'             => 1,
                'type'              => 'I',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 302,
                'name'              => 'Service Income',
                'parent_name'       => 'Income',
                'level'             => 1,
                'type'              => 'I',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 401,
                'name'              => 'Default Expense',
                'parent_name'       => 'Expense',
                'level'             => 1,
                'type'              => 'E',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 1,
                'depreciation'      => 1,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 402,
                'name'              => 'Material Purchase',
                'parent_name'       => 'Expense',
                'level'             => 1,
                'type'              => 'E',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 403,
                'name'              => 'Employee Salary',
                'parent_name'       => 'Expense',
                'level'             => 1,
                'type'              => 'E',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 404,
                'name'              => 'Machine Purchase',
                'parent_name'       => 'Expense',
                'level'             => 1,
                'type'              => 'E',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 405,
                'name'              => 'Maintenance Service',
                'parent_name'       => 'Expense',
                'level'             => 1,
                'type'              => 'E',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 501,
                'name'              => 'Non Current Liabilities',
                'parent_name'       => 'Liabilities',
                'level'             => 1,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 502,
                'name'              => 'Current Liabilities',
                'parent_name'       => 'Liabilities',
                'level'             => 1,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 10101,
                'name'              => 'Inventory',
                'parent_name'       => 'Non Current Asset',
                'level'             => 1,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 10201,
                'name'              => 'Cash & Cash Equivalent',
                'parent_name'       => 'Current Asset',
                'level'             => 2,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 10202,
                'name'              => 'Account Receivable',
                'parent_name'       => 'Current Asset',
                'level'             => 2,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 50201,
                'name'              => 'Account Payable',
                'parent_name'       => 'Current Liabilities',
                'level'             => 2,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 50202,
                'name'              => 'Employee Ledger',
                'parent_name'       => 'Current Liabilities',
                'level'             => 2,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 50203,
                'name'              => 'Tax',
                'parent_name'       => 'Current Liabilities',
                'level'             => 2,
                'type'              => 'L',
                'transaction'       => 2,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 1020101,
                'name'              => 'Cash In Hand',
                'parent_name'       => 'Cash & Cash Equivalent',
                'level'             => 3,
                'type'              => 'A',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 1020102,
                'name'              => 'Cash At Bank',
                'parent_name'       => 'Cash & Cash Equivalent',
                'level'             => 3,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 1020103,
                'name'              => 'Cash At Mobile Bank',
                'parent_name'       => 'Cash & Cash Equivalent',
                'level'             => 3,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 1020201,
                'name'              => 'Customer Receivable',
                'parent_name'       => 'Account Receivable',
                'level'             => 3,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            [
                'code'              => 1020202,
                'name'              => 'Loan Receivable',
                'parent_name'       => 'Account Receivable',
                'level'             => 3,
                'type'              => 'A',
                'transaction'       => 2,
                'general_ledger'    => 1,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
            // [
            //     'code'              => 5020101,
            //     'name'              => 'Supplier Name',
            //     'parent_name'       => 'Account Payable',
            //     'level'             => 3,
            //     'type'              => 'L',
            //     'transaction'       => 1,
            //     'general_ledger'    => 0,
            //     'customer_id'       => null,
            //     'supplier_id'       => null,
            //     'budget'            => null,
            //     'depreciation'      => null,
            //     'depreciation_rate' => 0.00,
            //     'status'            => 1,
            //     'created_by'        => 'SuperAdmin'
            // ],
            [
                'code'              => 10202010001,
                'name'              => '1-Walking Customer',
                'parent_name'       => 'Customer Receivable',
                'level'             => 4,
                'type'              => 'A',
                'transaction'       => 1,
                'general_ledger'    => 2,
                'customer_id'       => null,
                'supplier_id'       => null,
                'budget'            => 2,
                'depreciation'      => 2,
                'depreciation_rate' => 0.00,
                'status'            => 1,
                'created_by'        => 'SuperAdmin'
            ],
        ];
        foreach ($this->chart_of_accounts as $account) {
            ChartOfAccount::updateOrCreate($account);
        }
        
    }
}
